require 'pathname'

# Load IPs from ips.conf
ips_path = Pathname.new(__dir__) + 'ips.conf'
ips = {}
if ips_path.exist?
  File.readlines(ips_path).each do |line|
    k, v = line.strip.split('=')
    ips[k] = v
  end
else
  raise "ips.conf not found!"
end

SERVER_IP = ips['SERVER_IP']

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "HAMEUR-S" do |s|
    s.vm.hostname = "HAMEUR-S"
    s.vm.network "private_network", ip: SERVER_IP
    s.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "p2_HAMEUR-S"
    end
    s.vm.provision "shell", path: "scripts/install_k3s.sh"
  end
end
