apiVersion: v1
clusters:
- cluster:
    server: https://192.168.42.110:6443
    insecure-skip-tls-verify: true
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJR1hYRXhrYkdzVll3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelkwTlRNME1qSXlNQjRYRFRJMU1URXpNREl3TWpNME1sb1hEVEkyTVRFegpNREl3TWpNME1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJNam9TbHdaSy9wcDdnRFcKUlp3RjgxR3hkVUprSW5laEdpMWJBaXpIajRRL0FXUEUydkZVNVB2eGVwS2h3VnZUbkJnSjRpR1BWNzFNU0dRUwpFTjNFREFlalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUmNUQXpkbkVYcU5OMkpwclpmZnl1NTFMSTRKekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXJ2WFp1RWpQcklJQ2tqM1RjN2NacFNQbGUveERINnBJc1BkV04zUmtHbm9DSVFDb3F0QlRPZ2tZc1RIYgpiYzVUcHhlbU5HSklkQ2Z3aDZOaU9Oa2ZQd2dWb0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM05qUTFNelF5TWpJd0hoY05NalV4TVRNd01qQXlNelF5V2hjTk16VXhNVEk0TWpBeU16UXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM05qUTFNelF5TWpJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUlI1eTFFY3FPbkNnNGNDRkZpYU1uaHl5MmhGeGwwdkl5NS9aaWl6MU81CnpLclhjSEd4Um80MG9NNFY0NERpVy9ZTjA5NkloU2VyZ2NVVUdaRDBFMW5qbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVYRXdNM1p4RjZqVGRpYWEyWDM4cgp1ZFN5T0Njd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFJeFE3Y2FKejYrTm9vRWs1WG55VnE2QnNJRlg3TE5lCllRZWNVc3pHNXAxdUFpQkZnS3VQTHFJdlE3T2lhR09TaUNTUEswMXhIWUVLckNiOE9HSXpYckpoYXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFEVVR6WTVtV1gvd3FKZllTZkhOTVFSSW1CQzN3OWRXZHd6Nll0L0E4VmlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFeU9oS1hCa3IrbW51QU5aRm5BWHpVYkYxUW1RaWQ2RWFMVnNDTE1lUGhEOEJZOFRhOFZUaworL0Y2a3FIQlc5T2NHQW5pSVk5WHZVeElaQklRM2NRTUJ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
