Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "HAMEUR-S" do |s|
    s.vm.hostname = "HAMEUR-S"
    s.vm.network "private_network", ip: "192.168.42.110"
    s.vm.provider "virtualbox" do |v|
      v.memory = 2048  # ArgoCD needs more memory
      v.cpus = 2
      v.name = "p3_HAMEUR-S"
    end
    s.vm.provision "shell", path: "scripts/install_k3s.sh"
  end
end
